In [3]:
from sklearn.pipeline import Pipeline
##feature scaling
from sklearn.preprocessing import StandardScaler  ##transformation technique
from sklearn.linear_model import LogisticRegression #here LogiReg is the estimator

In [8]:
steps=[("standard_scaler",StandardScaler()),("classifier",LogisticRegression())]  #given in key-value pairs

In [9]:
steps


[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [11]:
pipe=Pipeline(steps)

In [14]:
##visualising pipeline
from sklearn import set_config


In [15]:
set_config(display="diagram")

In [16]:
pipe


Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [20]:
##creating dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000) ##X=(noOfSamples, features),y=no of classes


In [21]:
X.shape

(1000, 20)

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test=train_test_split(X,y,test_size=0.33, random_state=42)

In [25]:
X_train

array([[-0.15725379,  0.80234777,  0.43786653, ...,  0.84511926,
         0.21131135, -0.34122549],
       [ 0.7904378 , -0.21332024, -0.86666692, ...,  2.0404769 ,
         0.90217638,  1.1396531 ],
       [-0.20580487,  0.98324571,  0.55561128, ..., -0.57382475,
        -0.28016098, -1.6529773 ],
       ...,
       [ 1.12007021,  3.10238656, -0.24206705, ...,  1.55895094,
        -0.79686687,  0.57045684],
       [-0.14778672, -0.17439846, -1.17973038, ...,  0.73966785,
         0.32562139, -2.15624101],
       [ 0.26253458, -0.8256153 , -0.50386978, ..., -0.77701164,
         1.0823975 ,  2.21729117]])

In [27]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [28]:
y_pred=pipe.predict(X_test)

In [29]:
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,

Display a pipeline with standard scaler, dimensionality reduction and then estimator

In [32]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [34]:
steps=[("scaling",StandardScaler()),("PCA",PCA(n_components=3)),("SVC",SVC())]

In [37]:
pipe2=Pipeline(steps)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [39]:
 pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [40]:
y_pred=pipe2.predict(X_train)

In [41]:
y_pred

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,

In [42]:
#column transformer

In [46]:
from sklearn.impute import SimpleImputer

In [47]:
import numpy as np
numeric_processor=Pipeline(
    steps=[("imputation_mean",SimpleImputer(missing_values=np.nan, strategy="mean")),("scaler",StandardScaler())]
)

In [49]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [50]:
##categoical processing pipeline

In [53]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
categorical_processor=Pipeline(
    steps=[("imputation_constant",SimpleImputer(fill_value="missing", strategy="constant")),("scaler",StandardScaler()),("onehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [55]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('scaler', StandardScaler()),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [56]:
##combining processing techniques

In [58]:
from sklearn.compose import ColumnTransformer

In [59]:
preprocessor=ColumnTransformer([("categorical",categorical_processor,["gender","City"]),("numerical",numeric_processor,["age","height"])])

In [60]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('scaler', StandardScaler()),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [61]:
##adding estimator

In [62]:
from sklearn.pipeline import make_pipeline

In [63]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [65]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('scaler',
                                                                   StandardScaler()),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])